// svelte-renderer/src/routes/schedule/[line_id]/[stop_id]/ScheduleInfo.svelte
<script lang="ts">
	export let name: string;
	export let startDate: string;
	export let stopId: string;
</script>

<p class="text-[3mm]">
	<span class="font-semibold"> Horário da paragem</span>: {name}.
	<span class="font-semibold"> Código de paragem:</span> #{stopId}
	<span class="font-semibold"> Horário atualizado em:</span>
	{startDate}
</p>

// renderer/app/schedule/[line_id]/[stop_id]/ScheduleInfo.tsx
export default function ScheduleInfo({ name, startDate, stopId }:{name:string, startDate:string, stopId:string}) {
	return (
		<p className='text-[3mm]'>
			<span className='font-semibold'> Horário da paragem</span>: {name}.
			<span className='font-semibold'> Código de paragem:</span> #{stopId}
			<span className='font-semibold'> Horário atualizado em:</span> {startDate}
		</p>
	);
}
