// renderer/app/schedule/[line_id]/[direction_id]/[stop_id]/Header.tsx
export default function Header({ backgroundColor, color, lineId, headsigns, dataurl }: {backgroundColor: string, color: string, lineId:string, headsigns:string[], dataurl:string}) {
	const lineTypes:Record<string, string> = {
		'#3D85C6': 'P',
		'#C61D23': 'L',
		'#FDB71A': 'R',
		'#0C807E': 'M',
		'#BB3E96': 'I',
	};
	let lineType = lineTypes[backgroundColor] || '?';
	let fontSizes:Record<number, number> = {
		1: 17,
		2: 15,
		3: 12,
		4: 12,
		5: 10,
	};
	let fontSize = fontSizes[headsigns.length] || 10;
	return (

		<div className='p-[5mm] bg-black h-[30mm] text-white w-full flex items-center justify-between'>
			<div className='flex flex-row justify-start gap-[2mm] items-center'>
				<div className='text-center px-[10mm] py-2 font-bold rounded-full text-[40pt] leading-none flex items-center'
					style={{ backgroundColor, color }}>
					{lineId}
				</div>
				<div className='flex flex-row justify-start'>
					<div className='flex h-full flex-col justify-center leading-none gap-2 font-bold' style={{ fontSize: fontSize + 'pt' }}>
						{headsigns.map((headsign, index) => <div className='flex items-center' key={index}>
							<div className='flex items-center justify-center rounded-full mr-2'>
								<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2' strokeLinecap='round' strokeLinejoin='round'><path stroke='none' d='M0 0h24v24H0z' fill='none'/><path d='M5 12l14 0' /><path d='M13 18l6 -6' /><path d='M13 6l6 6' /></svg>
							</div>
							<div>
								{headsign}
							</div>
						</div>)}
					</div>
				</div>
			</div>
			<div className='flex gap-1 items-center'>
				{/* <Logo className='w-[45.6mm]' /> */}
				<div className='w-20 text-[0.5rem] font-bold leading-tight self-end text-right pb-[0.15rem]'>
						Consulte aqui o horário atualizado desta paragem
				</div>
				<div className='h-16 w-16 p-1 bg-white rounded-sm' dangerouslySetInnerHTML={{ __html: dataurl }}/>
			</div>
		</div>
	);
}

// svelte-renderer/src/routes/schedule/[line_id]/[stop_id]/Header.svelte
<script lang="ts">
	import Logo from "./logo.svelte";
	export let backgroundColor: string;
	export let color: string;
	export let lineId: string;
	export let firstStop: string;
	export let lastStop: string;
	const lineTypes: Record<string, string> = {
		"#3D85C6": "P",
		"#C61D23": "L",
		"#FDB71A": "R",
		"#0C807E": "M",
		"#BB3E96": "I",
	};
	let lineType = lineTypes[backgroundColor] || "?";
</script>

<div class="p-[5mm] bg-black h-[30mm] text-white w-full flex items-center">
	<div class="flex flex-row justify-between w-full">
		<div class="flex flex-row justify-start gap-[10mm]">
			<div>
				<Logo class="w-[45.6mm]" />
			</div>
			<div class="flex flex-row gap-[2.5mm] justify-start">
				<div class="">
					<div
						class="flex h-full w-[4mm] rounded-[5mm] flex-col justify-between"
						style:background-color={backgroundColor}
					>
						<div
							class="flex bg-white rounded-[5mm] h-[4mm] w-[4mm] text-black flex-row items-center justify-center"
						>
							<svg
								stroke="black"
								class="w-[12mm] h-[12mm] fill-transparent"
								viewBox="0 0 24 24"
								stroke-width="3"
								stroke-linecap="round"
								stroke-linejoin="round"
							>
								<path d="M6 9l6 6l6 -6" />
							</svg>
						</div>
						<div
							class="flex bg-black rounded-[5mm] text-white h-[4mm] w-[4mm] text-[3mm] font-bold flex-row items-center justify-center"
						>
							<p>{lineType}</p>
						</div>
						<div
							class="flex bg-white rounded-[5mm] h-[4mm] w-[4mm] text-black flex-row items-center justify-center"
						>
							<svg
								stroke="black"
								class="w-[12mm] h-[12mm]"
								viewBox="0 0 24 24"
								stroke-width="3"
								stroke-linecap="round"
								stroke-linejoin="round"
							>
								<path stroke="none" d="M0 0h24v24H0z" fill="none" />
								<path d="M18 6l-12 12" />
								<path d="M6 6l12 12" />
							</svg>
						</div>
					</div>
				</div>
				<div
					class="flex h-full flex-col justify-between text-[11pt] leading-none"
				>
					<p>{firstStop}</p>
					<p>{lastStop}</p>
				</div>
			</div>
		</div>
		<div
			class="text-center px-[10mm] py-[2mm] font-bold rounded-full text-[16mm] leading-none"
			style:background-color={backgroundColor}
			style:color
		>
			<p>{lineId}</p>
		</div>
	</div>
</div>
